version: '3'
services:
  db:
    image: mariadb
    container_name: dragon_store_db
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=dragondb
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_ROOT_PASSWORD=root