export const ITEM_LIST_ADMIN_REQUEST = "ITEM_LIST_ADMIN_REQUEST";
export const ITEM_LIST_ADMIN_SUCCESS = "ITEM_LIST_ADMIN_SUCCESS";
export const ITEM_LIST_ADMIN_FAIL = "ITEM_LIST_ADMIN_FAIL";

export const ORDER_LIST_ADMIN_REQUEST = "ORDER_LIST_ADMIN_REQUEST";
export const ORDER_LIST_ADMIN_SUCCESS = "ORDER_LIST_ADMIN_SUCCESS";
export const ORDER_LIST_ADMIN_FAIL = "ORDER_LIST_ADMIN_FAIL";

export const USER_LIST_REQUEST = "USER_LIST_REQUEST";
export const USER_LIST_SUCCESS = "USER_LIST_SUCCESS";
export const USER_LIST_FAIL = "USER_LIST_FAIL";

export const SALE_LIST_REQUEST = "SALE_LIST_REQUEST";
export const SALE_LIST_SUCCESS = "SALE_LIST_SUCCESS";
export const SALE_LIST_FAIL = "SALE_LIST_FAIL";

export const LIST_RESET = "LIST_RESET";

export const ADD_ITEM_REQUEST = "ADD_ITEM_REQUEST ";
export const ADD_ITEM_SUCCESS = "ADD_ITEM_SUCCESS ";
export const ADD_ITEM_FAIL = "ADD_ITEM_FAIL";
