export const CART_FETCH_REQUEST = "CART_FETCH_REQUEST";
export const CART_FETCH_SUCCESS = "CART_FETCH_SUCCESS";
export const CART_FETCH_FAIL = "CART_FETCH_FAIL";

export const CART_ADD_ITEM_REQUEST = "CART_ADD_ITEM_REQUEST";
export const CART_ADD_ITEM_SUCCESS = "CART_ADD_ITEM_SUCCESS";
export const CART_ADD_ITEM_FAIL = "CART_ADD_ITEM_FAIL";

export const CART_ADD_BATCH_REQUEST = "CART_ADD_BATCH_REQUEST";
export const CART_ADD_BATCH_SUCCESS = "CART_ADD_BATCH_SUCCESS";
export const CART_ADD_BATCH_FAIL = "CART_ADD_BATCH_FAIL";

export const CART_REMOVE_ITEM_REQUEST = "CART_REMOVE_ITEM_REQUEST";
export const CART_REMOVE_ITEM_SUCCESS = "CART_REMOVE_ITEM_SUCCESS";
export const CART_REMOVE_ITEM_FAIL = "CART_REMOVE_ITEM_FAIL";

export const CART_FETCH_ADDRESS_REQUEST = "CART_FETCH_ADDRESS_REQUEST";
export const CART_FETCH_ADDRESS_SUCCESS = "CART_FETCH_ADDRESS_SUCCESS";
export const CART_FETCH_ADDRESS_FAIL = "CART_FETCH_ADDRESS_FAIL";

export const CART_SAVE_SHIPPING_ADDRESS_FAIL =
  "CART_SAVE_SHIPPING_ADDRESS_FAIL";
export const CART_SAVE_SHIPPING_ADDRESS_REQUEST =
  "CART_SAVE_SHIPPING_ADDRESS_REQUEST";
export const CART_SAVE_SHIPPING_ADDRESS_SUCCESS =
  "CART_SAVE_SHIPPING_ADDRESS_SUCCESS";
export const CART_SAVE_PAYMENT_METHOD = "CART_SAVE_PAYMENT_METHOD";

export const EMPTY_CART = "EMPTY_CART";
