export const ITEM_LIST_REQUEST = "ITEM_LIST_REQUEST";
export const ITEM_LIST_SUCCESS = "ITEM_LIST_SUCCESS";
export const ITEM_LIST_FAIL = "ITEM_LIST_FAIL";

export const ITEM_DETAILS_REQUEST = "ITEM_DETAILS_REQUEST";
export const ITEM_DETAILS_SUCCESS = "ITEM_DETAILS_SUCCESS";
export const ITEM_DETAILS_FAIL = "ITEM_DETAILS_FAIL";
export const ITEM_DETAILS_RESET = "ITEM_DETAILS_RESET";

export const ITEM_SEARCH_REQUEST = "ITEM_SEARCH_REQUEST";
export const ITEM_SEARCH_SUCCESS = "ITEM_SEARCH_SUCCESS";
export const ITEM_SEARCH_FAIL = "ITEM_SEARCH_FAIL";
export const ITEM_SEARCH_RESET = "ITEM_DETAILS_RESET";

export const ITEM_UPDATE_REQUEST = "ITEM_UPDATE_REQUEST";
export const ITEM_UPDATE_SUCCESS = "ITEM_UPDATE_SUCCESS";
export const ITEM_UPDATE_FAIL = "ITEM_UPDATE_FAIL";
